Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "salt", "/srv/salt/"
  config.vm.synced_folder "pillar", "/srv/pillar" 
  config.vm.synced_folder "../", "/srv/formulas/mesos-formula" 

  config.vm.network "forwarded_port", guest: 5050, host: 5050
  
  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
  # get the git development version of salt
    salt.install_type = 'git'
    salt.install_args = 'develop'
    salt.colorize = true
    salt.log_level = 'debug'
    salt.verbose = true
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
